name: Newman Test Run
on:
  push:
    branches:
    - main
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      -   
       name: "Install newman"
       run: npm install -g newman
      - 
       name: "Install newman reporter"
       run: npm install -g newman-reporter-htmlextra
      - 
       name: "Run tests"
       run: newman run "https://api.postman.com/collections/8692884-f6a06efb-05d4-4ee1-969d-65cf737fdafb?access_key=PMAT-01H2DNGKE675AR9XK4YAGQGYD6" --reporters cli,htmlextra --reporter-htmlextra-export testReport.html
      - name: Publish report
        uses: MeilCli/slack-upload-file@v1
        with:
          file_path: './tests/htmlreport.html'
          file_name: 'testReport.html'
          file_type: 'html'
